CREATE TABLE CLIENTE(
    dni VARCHAR(9) PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    telf INT NOT NULL,
    edad INT NOT NULL,
    fnac DATE NOT NULL,
    especificaciones VARCHAR(250) DEFAULT 'SIN ESPECIFICAR'
);
CREATE TABLE TRABAJADOR(
    COD_TRABAJADOR INT PRIMARY KEY AUTO_INCREMENT,
    dni VARCHAR(9) UNIQUE,
    nombre VARCHAR(20) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    horario VARCHAR(60) NOT NULL
);
CREATE TABLE PRODUCTO(
    cod_prod INT PRIMARY KEY AUTO_INCREMENT,
    stock INT NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    marca VARCHAR(30) NOT NULL
);
CREATE TABLE TRATAMIENTO(
    cod_trat INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(40) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    precio DOUBLE NOT NULL,
    duracion_media_horas DOUBLE NOT NULL
);
CREATE TABLE PRODUCTO_TRATAMIENTO(
    cod_producto INT REFERENCES PRODUCTO(cod_prod),
    cod_tratamiento INT REFERENCES TRATAMIENTO(cod_trat),
    CONSTRAINT PK_PROD_TRAT PRIMARY KEY(cod_producto, cod_tratamiento)
);
CREATE TABLE CITA(
    cod_cita INT PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    HORA TIME,
    observaciones VARCHAR(250) DEFAULT 'NO HAY OBSERVACIONES',
    tratamiento INT NOT NULL REFERENCES TRATAMIENTO(cod_trat),
    trabajadorEncargado INT NOT NULL REFERENCES TRABAJADOR(COD_TRABAJADOR),
    clientePedido VARCHAR(9) NOT NULL REFERENCES CLIENTE(dni)
);